### ISSUE TITLE
docker hub?

### ISSUE THREAD

**Issue by rolocampusano** [b1n4ryj4n/koreader-sync#1]
Hi! Can you create an image in docker hub? My server doesnt have docker compose built in and I tried using my laptop but it has a different architecture (ARM vs x86). :(

**Comment by b1n4ryj4n** [comment]
hi you can try `docker pull b1n4ryj4n/koreader-sync` or `docker pull b1n4ryj4n/koreader-sync:arm`

**Comment by rolocampusano** [comment]
Thanks! It works! :)

**Comment by rolocampusano** [comment]
Btw. This is another question thats why I closed the issue. Have you been able to sync highlights and notes? Also, have you found a way to keep track of what books you have read? Thanks!

**Comment by b1n4ryj4n** [comment]
> Have you been able to sync highlights and notes?

Sry i wont use koreader to highlighting stuff or taking notes

> Also, have you found a way to keep track of what books you have read?

Sadly not an optimal way. I use git (selfhosted gitea) for now until i find some good alternative. Basically two branches:
- "main" = all books i have
- "koreader" = all books (without finished ones)
