### ISSUE TITLE
I want to made a little donation

### ISSUE THREAD

**Issue by Edo78** [b1n4ryj4n/koreader-sync#2]
I really appreciate your work and I'd like to donate a (small) amount of money as a way to thank you. Do you have a buymeacoffee account or something similar?

**Comment by b1n4ryj4n** [comment]
Thank you very much. Im very appreciate your support but you don't need to donate me some money.

I have an Algorand Wallet (it's a cryptocurrency) if you really want to donate something: 725KWJYCC36NW4U6BNMVD7SI5QQJHJNUJF6BSCX5O3UHMS7SWMJM2EOW7Y

**Comment by Edo78** [comment]
I have no clue on how to manage crypto :cry: 
If you'll ever change your mind let me know. This is the only sync service for koreader with a docker image for arm cpu and it save me the time and effort to try to create one by myself.

**Comment by b1n4ryj4n** [comment]
> I have no clue on how to manage crypto 😢

https://www.coinbase.com/ is for sure the easiest one.
