### ISSUE TITLE
Docker hub image - unable to mount volume

### ISSUE THREAD

**Issue by Wri84** [b1n4ryj4n/koreader-sync#4]
Hi,

I'm currently searching for an ereader app that supports OPDS as well progress syncing across devices. Koreader seems to offer both with the sync server and I've tried to spin up your image from docker hub using compose on my system. 

This works fine and koreader can connect as well as push updates. 

However, to backup the container state I would like to mount the database to a persistent volume through docker compose and backup this directory. But when I try to mount the "/app" directory, the container no longer starts with the following error

> ERROR:    Error loading ASGI app. Could not import module "kosync".

If I don't mount any volumes, the container works fine. 

Could you modify the image so that it is possible to mount the database to a volume and have it backed up externally?  

Someone on stackoverflow posted this as a solution for his app https://stackoverflow.com/a/71875029 
Since in your image, "/app" is directly in the root of the container image, this doesn't work. Heres my compose snippet for your container:

```
# Koreader-Sync
  koreader-sync:
    image: b1n4ryj4n/koreader-sync:latest
    container_name: koreader-sync
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      UID: $PUID
      GID: $PGID
      TZ: $TZ  
    volumes:
      - $DOCKERDIR/koreader-sync:/app

**Comment by b1n4ryj4n** [comment]
oO "/app/data" is my root for volumes where the 'json' db-file gets stored.

Try to change your volumes in docker-compose.yml to
 ```
    volumes:
      - $DOCKERDIR/koreader-sync:/app/data
 ```
im sure it will work than.
