### ISSUE TITLE
Database migration

### ISSUE THREAD

**Issue by nlafevers** [b1n4ryj4n/koreader-sync#6]
I have koreader-sync running on a Google Cloud VM, and it works perfectly.  But if I try to create a new VM, setup koreader-sync there, how do I copy over user and sync progress to the database on the new server?

**Comment by b1n4ryj4n** [comment]
hi there,
try the following steps:

1. stop the docker container on both servers
2. copy the db.json from the old server data folder to the new server data folder (pay attention to file permissions)
3. start the new docker container

**Comment by nlafevers** [comment]
Maybe that would work, but I'm not using docker so I can't test it.  Because of how the passwords are hashed, that approach doesn't work with the non-docker implementation.  It is possible to just copy over the database to the new server, manually edit the file to delete the users (leaving the progress syncs), then re-register from Koreader using the same usernames.  This re-establishes your synced progress.  I was just hoping there was a better way to migrate data, especially if there are a larger number of users.

**Comment by b1n4ryj4n** [comment]
> Because of how the passwords are hashed, that approach doesn't work with the non-docker implementation.

It doesn’t matter whether you run it on Docker or not—the hash is generated directly by KOReader, not the sync server.

> especially if there are a larger number of users

Sorry, but this version of the sync server isn't designed to handle a large number of users or to manage them efficiently. (I might add that feature in the future.)

> I was just hoping there was a better way to migrate data

Feel free to check out TinyDB; you could use it to implement a way to remove users. (Note: This hasn't been tested—it’s just written in the GitHub reply section)

```
from tinydb import TinyDB, Query

# db path
db = TinyDB('data/db.json')

# tables
users_table = db.table('users')
documents_table = db.table('documents')

# query object
User = Query()

# 1. delete "user1"
users_to_delete = users_table.search(User.username == 'user1')
for user in users_to_delete:
    users_table.remove(doc_ids=[int(doc_id) for doc_id in user.keys()])

# 2. delete all documents from "user1"
documents_to_delete = documents_table.search(User.username == 'user1')
for doc in documents_to_delete:
    documents_table.remove(doc_ids=[int(doc_id) for doc_id in doc.keys()])

print("all entries for 'user1' deleted")
```
